queue_rules:
  - name: default
    merge_conditions:
      - check-success=tests (macos-latest)
      - check-success=tests (ubuntu-latest)
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label=merge-queue
    actions:
      queue: {}
