on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v30
      - name: Get release notes
        id: release-notes
        run: ./scripts/print-release-notes.sh ${{ github.ref }}
      - name: Build binaries
        run: |
          mkdir -p build
          cd build
          nix-shell -I nixpkgs=channel:nixos-unstable-small --pure -p gox -p go --run "gox -os '!windows' -osarch '!darwin/386' .."
          gzip *
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "${{ steps.release-notes.outputs.release_name }}"
          body: "${{ steps.release-notes.outputs.body }}"
          prerelease: false
      - name: Upload binaries
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
