name: "Test"
on:
  pull_request:
  push:
  schedule:
    - cron:  '31 2 * * *'
jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v23
    - run:
        nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
    - run:
        nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz --pure --run "TMPDIR=/tmp TEST_ASSETS=$(pwd)/test NIX_SSL_CERT_FILE=$NIX_SSL_CERT_FILE go test"
      # tests rely on `--store`, which is not supported on macOS
      if: matrix.os == 'ubuntu-latest'
    - run:
        nix-shell --argstr nixVersion nix_2_15 -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz --pure --run "TMPDIR=/tmp TEST_ASSETS=$(pwd)/test NIX_SSL_CERT_FILE=$NIX_SSL_CERT_FILE go test"
      # tests rely on `--store`, which is not supported on macOS
      if: matrix.os == 'ubuntu-latest'
    - run:
        nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz --pure -p gox -p go --run "gox -os '!windows' -osarch '!darwin/386' ."
      # no need to run this on multiple platforms
      if: matrix.os == 'ubuntu-latest'
